In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
t0 = tf.constant(3)

In [3]:
print('Created a constant type tensor')

print("The tensor\n", t0)
print("To numpy\n", t0.numpy())
print("Rank of tensor", tf.rank(t0))

Created a constant type tensor
The tensor
 tf.Tensor(3, shape=(), dtype=int32)
To numpy
 3
Rank of tensor tf.Tensor(0, shape=(), dtype=int32)


In [4]:
print("Creating a 1D Tensor.")
t1 = tf.constant([3,2,5,8])

print("The tensor\n", t1)
print("To numpy\n", t1.numpy())
print("Rank of tensor", tf.rank(t1))

Creating a 1D Tensor.
The tensor
 tf.Tensor([3 2 5 8], shape=(4,), dtype=int32)
To numpy
 [3 2 5 8]
Rank of tensor tf.Tensor(1, shape=(), dtype=int32)


In [5]:
print("Creating a 2D Tensor.")
t2 = tf.constant([
    [1,3,4],
    [3,2,5],
    [3,5,7]
])

print("The tensor\n", t2)
print("To numpy\n", t2.numpy())
print("Rank of tensor", tf.rank(t2))

Creating a 2D Tensor.
The tensor
 tf.Tensor(
[[1 3 4]
 [3 2 5]
 [3 5 7]], shape=(3, 3), dtype=int32)
To numpy
 [[1 3 4]
 [3 2 5]
 [3 5 7]]
Rank of tensor tf.Tensor(2, shape=(), dtype=int32)


In [6]:
print("Creaing a 3D Tensor")

t3 = tf.constant([[[1,3,4], [2,2,2]], [[1,1,1], [0,0,0]], [[3,3,3], [4,4,4]]])

print("The tensor\n", t3)
print("To numpy\n", t3.numpy())
print("Rank of tensor", tf.rank(t3))

Creaing a 3D Tensor
The tensor
 tf.Tensor(
[[[1 3 4]
  [2 2 2]]

 [[1 1 1]
  [0 0 0]]

 [[3 3 3]
  [4 4 4]]], shape=(3, 2, 3), dtype=int32)
To numpy
 [[[1 3 4]
  [2 2 2]]

 [[1 1 1]
  [0 0 0]]

 [[3 3 3]
  [4 4 4]]]
Rank of tensor tf.Tensor(3, shape=(), dtype=int32)


In [7]:
print("Creating a variable tensor and giving a name 'var1'")
tv1 = tf.Variable(2, dtype=tf.float32, name='var1')

print("The tensor", tv1)
print("To numpy", tv1.numpy())

Creating a variable tensor and giving a name 'var1'
The tensor <tf.Variable 'var1:0' shape=() dtype=float32, numpy=2.0>
To numpy 2.0


In [8]:
print("Casting a float tensor to integer")
tv1 = tf.cast(tv1, tf.int32)

print("The tensor", tv1)
print("To numpy", tv1.numpy())

Casting a float tensor to integer
The tensor tf.Tensor(2, shape=(), dtype=int32)
To numpy 2


In [9]:
print("Accessing elements in a tensor.")
tv2 = tf.Variable([2,4,6,8,10])

print(f"The tensor {tv2}")
print(f"First element {tv2[0]}")
print(f"First 3 elements {tv2[:3]}")

Accessing elements in a tensor.
The tensor <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  4,  6,  8, 10])>
First element 2
First 3 elements [2 4 6]


In [10]:
print("Creating a 4x3 tensor with random values that form a normal distribution.")
tv3 = tf.random.normal([4, 3])
print(tv3)

print("This is a tf.random.normal value and it doesn't support changes. It is immutable. To alter values, it ought to be converted into a variable.")

Creating a 4x3 tensor with random values that form a normal distribution.
tf.Tensor(
[[-0.8326308   0.902288   -0.8630641 ]
 [-0.84575623  0.9185586  -1.2197354 ]
 [-0.19613984 -0.70134246 -0.10182567]
 [ 1.1017545   1.9546351   0.45413843]], shape=(4, 3), dtype=float32)
This is a tf.random.normal value and it doesn't support changes. It is immutable. To alter values, it ought to be converted into a variable.


In [11]:
tv4 = tf.Variable(tv3)

print("TV4\n", tv4)

TV4
 <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.8326308 ,  0.902288  , -0.8630641 ],
       [-0.84575623,  0.9185586 , -1.2197354 ],
       [-0.19613984, -0.70134246, -0.10182567],
       [ 1.1017545 ,  1.9546351 ,  0.45413843]], dtype=float32)>


In [12]:
print("Now, that tv4 is a variable, it supports item assignment. Let's alter the first element in the first row.")
tv4[0, 0].assign(99999)

Now, that tv4 is a variable, it supports item assignment. Let's alter the first element in the first row.


<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[ 9.9999000e+04,  9.0228802e-01, -8.6306411e-01],
       [-8.4575623e-01,  9.1855860e-01, -1.2197354e+00],
       [-1.9613984e-01, -7.0134246e-01, -1.0182567e-01],
       [ 1.1017545e+00,  1.9546351e+00,  4.5413843e-01]], dtype=float32)>

In [13]:
print("Altering the entire first row.")
tv4[0, :].assign([9,9,9])

Altering the entire first row.


<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[ 9.        ,  9.        ,  9.        ],
       [-0.84575623,  0.9185586 , -1.2197354 ],
       [-0.19613984, -0.70134246, -0.10182567],
       [ 1.1017545 ,  1.9546351 ,  0.45413843]], dtype=float32)>

In [14]:
print("Creating a matrix of just ones.")
tf.ones([3,3])

Creating a matrix of just ones.


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
print("Creating a matrix of just zeros.")
tf.zeros([3,3])

Creating a matrix of just zeros.


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [16]:
print("Reshaping tensors.")
tv5 = tf.Variable(tv4)
print("The tensor\n", tv5)
print("Shape of tensor", tv5.shape)
tv5 = tf.reshape(tv5, [6, 2])
print("The tensor after reshaping\n", tv5)
print("Shape after reshaping", tv5.shape)

Reshaping tensors.
The tensor
 <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 9.        ,  9.        ,  9.        ],
       [-0.84575623,  0.9185586 , -1.2197354 ],
       [-0.19613984, -0.70134246, -0.10182567],
       [ 1.1017545 ,  1.9546351 ,  0.45413843]], dtype=float32)>
Shape of tensor (4, 3)
The tensor after reshaping
 tf.Tensor(
[[ 9.          9.        ]
 [ 9.         -0.84575623]
 [ 0.9185586  -1.2197354 ]
 [-0.19613984 -0.70134246]
 [-0.10182567  1.1017545 ]
 [ 1.9546351   0.45413843]], shape=(6, 2), dtype=float32)
Shape after reshaping (6, 2)


In [17]:
print("Condition based selection of elements in a tensor.")
tv6 = tf.random.stateless_normal(shape=[4, 3], seed=(0, 0))
print("The tensor", tv6)

print("\nCondition: Element value less than 0:\n", tv6<0)
print("\nCondition: Element value less than 0. Fetching specific elements itself:\n", tv6[tv6<0])
print("\nCondition: Element value less than 0. Fetching elements' position:\n", tf.where(tv6<0))

Condition based selection of elements in a tensor.
The tensor tf.Tensor(
[[-1.697034   -0.4813767  -0.6622369 ]
 [ 0.08701117 -1.0001622   0.94347405]
 [ 0.61669475  0.21356511 -0.1427695 ]
 [-0.5535083   1.2846227   1.5292794 ]], shape=(4, 3), dtype=float32)

Condition: Element value less than 0:
 tf.Tensor(
[[ True  True  True]
 [False  True False]
 [False False  True]
 [ True False False]], shape=(4, 3), dtype=bool)

Condition: Element value less than 0. Fetching specific elements itself:
 tf.Tensor([-1.697034  -0.4813767 -0.6622369 -1.0001622 -0.1427695 -0.5535083], shape=(6,), dtype=float32)

Condition: Element value less than 0. Fetching elements' position:
 tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [1 1]
 [2 2]
 [3 0]], shape=(6, 2), dtype=int64)


### Arithematic operations on tensors

In [18]:
a = tf.Variable([1,2,3])
print("A:", a)
b = tf.Variable([4,5,6])
print("B:", b)
print("")
print("Addition:", a+b)
print("Element-wise multiplication:", a*b)
print("Division:", a/b)
print("Modulus:", a%b)

A: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
B: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6])>

Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Element-wise multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
Modulus: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [19]:
print("Dot product along axis 0:\n", tf.tensordot(a=a, b=b, axes=0))
print("Dot product along axis 1:", tf.tensordot(a=a, b=b, axes=1).numpy())

Dot product along axis 0:
 tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)
Dot product along axis 1: 32


In [20]:
print("Adding to tensors:", tf.add(a, b))
print("Power function:", tf.pow(a, 3))
print("\nSquare root function requires a floating type data. We'll cast the variable 'a'.")
print("Square Root:", tf.sqrt(tf.cast(a, tf.float32)))
print("\nExponential function requires a floating type data. We'll cast the variable 'a'.")
print("Exponential:", tf.exp(tf.cast(a, tf.float32), 0.5))
print("\nLogarithm function requires a floating type data. We'll cast the variable 'a'.")
print("Logarithm:", tf.math.log(tf.cast(a, tf.float32)))

Adding to tensors: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Power function: tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)

Square root function requires a floating type data. We'll cast the variable 'a'.
Square Root: tf.Tensor([1.        1.4142135 1.7320508], shape=(3,), dtype=float32)

Exponential function requires a floating type data. We'll cast the variable 'a'.
Exponential: tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)

Logarithm function requires a floating type data. We'll cast the variable 'a'.
Logarithm: tf.Tensor([0.        0.6931472 1.0986123], shape=(3,), dtype=float32)


In [21]:
mat1 = tf.Variable(np.random.randint(1, 5, [4, 4]))
mat2 = tf.Variable(np.random.randint(6, 10, [4, 4]))

print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)

print("\nElement-wise Multiplication:\n", mat1*mat2)
print("\n\nMatrix Multiplication:\n", tf.matmul(mat1, mat2))

Matrix 1:
<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[1, 1, 4, 3],
       [1, 2, 2, 4],
       [4, 3, 3, 1],
       [2, 3, 1, 3]])>
Matrix 2:
 <tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[8, 7, 6, 9],
       [6, 9, 7, 9],
       [9, 6, 9, 9],
       [9, 6, 7, 7]])>

Element-wise Multiplication:
 tf.Tensor(
[[ 8  7 24 27]
 [ 6 18 14 36]
 [36 18 27  9]
 [18 18  7 21]], shape=(4, 4), dtype=int32)


Matrix Multiplication:
 tf.Tensor(
[[77 58 70 75]
 [74 61 66 73]
 [86 79 79 97]
 [70 65 63 75]], shape=(4, 4), dtype=int32)


### Determinant of a matrix.

In [22]:
mat1 = tf.cast(mat1, tf.float32)
print("Determinant of the matrix 1:", tf.linalg.det(mat1))

Determinant of the matrix 1: tf.Tensor(10.000003, shape=(), dtype=float32)


### Eigen values of a matrix.

In [23]:
eigen_values = tf.linalg.eigvals(mat1)
print("Eigen Values of  matrix 1:\n", eigen_values)

Eigen Values of  matrix 1:
 tf.Tensor([ 9.50372   +0.j -3.0684762 +0.j  2.692134  +0.j -0.12737617+0.j], shape=(4,), dtype=complex64)


### Transpose of a matrix.

In [24]:
transpose_mat1 = tf.transpose(mat1)
print("Matrix 1:\n", mat1)
print("\nTranspose of matrix 1:\n", transpose_mat1)

Matrix 1:
 tf.Tensor(
[[1. 1. 4. 3.]
 [1. 2. 2. 4.]
 [4. 3. 3. 1.]
 [2. 3. 1. 3.]], shape=(4, 4), dtype=float32)

Transpose of matrix 1:
 tf.Tensor(
[[1. 1. 4. 2.]
 [1. 2. 3. 3.]
 [4. 2. 3. 1.]
 [3. 4. 1. 3.]], shape=(4, 4), dtype=float32)


### Concatenating 2 tensors.

In [25]:
mat2 = tf.cast(mat2, tf.float32)
concat_tensor = tf.concat([mat1, mat2], axis=1)
print("Concatenated tensor:\n", concat_tensor)

Concatenated tensor:
 tf.Tensor(
[[1. 1. 4. 3. 8. 7. 6. 9.]
 [1. 2. 2. 4. 6. 9. 7. 9.]
 [4. 3. 3. 1. 9. 6. 9. 9.]
 [2. 3. 1. 3. 9. 6. 7. 7.]], shape=(4, 8), dtype=float32)
